# Generated by Django 5.1.2 on 2024-11-19 00:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='andamento', max_length=10)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projetos.projetos')),
            ],
        ),
       
    ]
