# Generated by Django 5.1.2 on 2024-11-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='andamento', max_length=10),
        ),
    ]
