# Generated by Django 5.1.2 on 2024-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0004_convites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='concluida',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
