# Generated by Django 5.1.2 on 2024-11-13 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0005_alter_colaboradores_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL),
        ),
    ]
