# Generated by Django 5.1.2 on 2024-11-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projetos', '0005_alter_colaboradores_user'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
